services:
  # Bazarr - Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: "service:gluetun"
    # networks:
    #  - default
    # ports:
    #  - "6767:6767"
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $DATADIR/data/media/shows:/tv
      - $DATADIR/data/media/movies:/movies
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      WEBUI_PORT: 6767
