services:
  # Sonarr - TV Shows Management
  # Set url_base in sonarr settings if using PathPrefix
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: "service:gluetun"
    # networks:
    #  - default
    # ports:
    #  - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonar:/config
      - $DATADIR/data/media/shows:/data/shows1
      - $DATADIR/downloads:/data/downloads 
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      WEBUI_PORT: 8989
