services:
  # ZeroTier-One - Private Network over Internet
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - $DOCKERDIR/appdata/zerotier:/var/lib/zerotier-one
